[package]
name = "obs-shader-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obs-wrapper = "0.4.0"

[lib]
name = "obsshaderplugin"
crate-type = ["cdylib"]